# CHAMPS
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/42
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/Backward
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/barriere
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/Car
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/Death
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/ex
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/Gagnant
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/jumper
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/lde
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/leeloo
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/mat
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/maxidef
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/mortel
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/new
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/Octobre_Rouge_V4.2
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/sebc
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/slider2
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/Survivor
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/tdc2
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/tdc3
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/tdc4
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/Torpille
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/toto   
# EXAMPLES
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/examples/bee_gees   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/examples/bigzork  
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/examples/fluttershy   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/examples/helltrain   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/examples/turtle   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/examples/zork  
# CHAMPIONSHIP 2014
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/bguy/sam_2.0   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/bjacob/doge   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/brandazz/Rainbow_dash
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/cdivry/youforkmytralala
sh script.sh  /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/clafleur/big_feet
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/dcohen/loose
sh script.sh  /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/ekocevar/mandragore   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/esusseli/gedeon
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/evlasova/terminator
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/fcorre/ultimate-surrender
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/gbir/_   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/gjestin/salamahenagalabadoun
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/gleger/Machine-gun   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/gmange/corelol   
sh script.sh  /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/gpetrov/MarineKing   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/gudepard/Kappa   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/hmichals/Wall   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/hmoutaou/Misaka_Mikoto
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/kelickel/Varimathras   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/kmonrose/justin_bee   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/ldesgoui/_honeybadger   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/lseguin/skynet   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/lsirigna/live   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/mbacoux/meowluigi   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/mconraux/dubo   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/rabid-on/jinx
sh script.sh  /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/rmasse/THUNDER   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/sbuono/Asombra   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/srabah-m/littlepuppy   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/tdemay/champ   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/vrey/darksasuke   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2014/ybouvet/casimir  
# CHAMPIONSHIP 2014
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/adenis/Explosive_Kitty   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/agregoir/Kittystrophic   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/gnebie/ultima   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/iburel/gateau   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/jaustry/mise_a_jour_windows95   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/nolivier/run_Kitty_RUN   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/pzarmehr/overwatch   
sh script.sh /Users/mkorniie/Downloads/vm_champs/champs/championships/2017/tbillard/Douceur_power   